
  CREATE TABLE "TPCH"."TB_CANDIDATE_VIEW" 
   (	"CMV_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CMV_DDL_CREATE" CLOB NOT NULL ENABLE, 
	"CMV_COST" NUMBER(19,0) NOT NULL ENABLE, 
	"CMV_PROFIT" NUMBER(19,0) NOT NULL ENABLE, 
	"CMV_STATUS" CHAR(1 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "TB_CANDIDATE_VIEW_PK" PRIMARY KEY ("CMV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("CMV_DDL_CREATE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

  
CREATE TABLE "TPCH"."TB_WORKLOAD" 
   ("WLD_SQL" CLOB NOT NULL ENABLE, 
	"WLD_PLAN" CLOB NOT NULL ENABLE, 
	"WLD_CAPTURE_COUNT" NUMBER(*,0) NOT NULL ENABLE, 
	"WLD_ANALYZE_COUNT" NUMBER(*,0) NOT NULL ENABLE, 
	"WLD_TYPE" CHAR(1 BYTE) NOT NULL ENABLE, 
	"WLD_RELEVANCE" NUMBER(*,0) NOT NULL ENABLE 	 
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("WLD_SQL") STORE AS SECUREFILE "SYS_LOB0000092016C00002$$"(
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("WLD_PLAN") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;


alter table "TPCH"."TB_WORKLOAD" add WLD_ID numeric(10);


create sequence wld_id_seq 
start with 1 
increment by 1 
nomaxvalue; 


create trigger wld_id_trigger
before insert on tb_workload
for each row
begin
select wld_id_seq.nextval into :new.wld_id from TB_WORKLOAD;
end;